title: yanavik.art
logo: 
description: >
this is placeholder text 

this is also placeholder text

please do not fall apart.
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
