title: yanavik.art
logo: https://i.imgur.com/SpZMeHW.png
description: "<br><a href="https://cara.app/yanavik">Cara (Digital Art Portfolio)</a><br><a href="https://www.youtube.com/@straydotmp4">YouTube</a><br><a href="https://yanavik.printify.me">T-Shirts</a><br><b>uvx@yanavik.art</b>"
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
