title: yanavik.art
logo: 
description: "Hi there! My name is Uli and I'm a graphic designer with a keen interest in hand-lettering and illustration.<br><br>I primarily specialize in advertising and branding (both print and digital), but I also have experience with merchandise design. I am currently available for work on a short-term commission/contract basis.<br><br>* * *<br><br><b>uvc@yanavik.art</b>"
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
