title: yanavik.art
logo: https://i.imgur.com/SpZMeHW.png
description: "<br>I'm Uli and graphic design might be my passion. I'm currently available on a short-term contract/part-time basis.<br>Feel free to shoot me an e-mail:<br><br><b>uvx@yanavik.art</b>"
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
