title: yanavik.art
logo: https://i.imgur.com/SpZMeHW.png
description: "<br>I'm Uli and graphic design might be my passion. Feel free to shoot me an e-mail:<br><br><b>uvx@yanavik.art</b>"
nav:
  - title: HOME
    url: /
  - title: "2025"
    url: /2025.md
  - title: "2024"
    url: /2024.md
  - title: "2023"
    url: /2023.md
  - title: "2022"
    url: /2022.md
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
