title: yanavik.art
logo: https://i.imgur.com/SpZMeHW.png
description: "<br>I'm Uli and graphic design might be my passion. Feel free to shoot me an e-mail:<br><br><b>uvx@yanavik.art</b><br><br>I'm also on <i>Cara</i> and <i>Bluesky</i> -- I'm <b>yanavik</b> on both platforms."
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
