title: ART & DESIGN
logo: https://i.imgur.com/8A3pOwN.png
description: This is a test to see if this value will override the GitHub one. 
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
