title: yanavik.art
logo: https://i.imgur.com/SpZMeHW.png
description: "<br>Feel free to contact me:<br><br><b>uvx@yanavik.art</b>"
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
